version: '2.1'

services:
 mongo:
      image: mongo:4.0.10
      ports:
        - 27017:27017
      volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        - ./mongo-volume:/data/db